Repository GuvendeKal/guvendekal.org, pull requests merged in 2024-11, with the labels that each got.

#110 2 Faktörlü Doğrulama
  docs/2-faktorlu-dogrulama.md
  docs/images/enteAuth.png
Labels: dökümantasyon, geliştirme

#112 2FA hataları düzeltildi
  docs/2-faktorlu-dogrulama.md
Labels: dökümantasyon, geliştirme

#114 RSS istemci kismi eklendi.
  docs/images/freshrss.png
  docs/images/miniflux.png
  docs/katkida-bulunanlar.md
  docs/rss-istemcileri.md
  docs/sifre-yoneticileri.md
Labels: dökümantasyon, geliştirme

#119 Footer'a public domain görseli eklendi.
  docs/images/cc0.png
  footer-plugin.js
Labels: geliştirme

#120 Hatalı bilgi düzeltmesi
  docs/sifre-yoneticileri.md
Labels: dökümantasyon, geliştirme

#125 Update tor-agi.md
  docs/katkida-bulunanlar.md
  docs/tor-agi.md
Labels: dökümantasyon, geliştirme

#128 Uygulama mağazaları eklendi
  docs/README.md
  docs/_sidebar.md
  docs/images/f-droid.png
  docs/images/gog.png
  docs/uygulama-magazalari.md
Labels: dökümantasyon, geliştirme, yardım lazım

#132 Update dns.md
  docs/dns.md
  docs/katkida-bulunanlar.md
Labels: dökümantasyon, geliştirme

#129 Anytype (Not alma uygulaması)
  docs/images/anytype.png
  docs/not-alma.md
Labels: dökümantasyon, geliştirme

#133 AuroraStore-magazalari.md
  docs/uygulama-magazalari.md
Labels: dökümantasyon, geliştirme

#137 Update README.md
  docs/README.md
Labels: dökümantasyon, geliştirme

#118 Sözlük eklemeleri --genel
  docs/sozluk.md
Labels: dökümantasyon, geliştirme, yardım lazım
