Repository GuvendeKal/guvendekal.org, pull requests merged in 2024-10, with the labels that each got.

#12 Katkı sağlama hakkında dokümentasyon
  CONTRIBUTING.md
Labels: documentation, enhancement

#24 mail services added
  docs/images/proton-mail.png
  docs/images/thunderbird.png
  docs/images/tutanota-mail.png
  docs/katkida-bulunanlar.md
  docs/posta-servisleri.md
Labels: documentation, enhancement

#29 Arama motorları eklendi
  docs/arama-motorlari.md
  docs/images/brave.png
  docs/images/duckduckgo.png
  docs/images/searx.png
Labels: documentation, enhancement

#33 Açık Kaynak, Mahremiyet ve Güvenlik sayfaları eklendi
  docs/README.md
  docs/_sidebar.md
  docs/acik-kaynak.md
  docs/arama-motorlari.md
  docs/dns.md
  docs/gizlilik.md
  docs/guvenlik.md
  docs/images/Android.png
  docs/images/Apache.png
  docs/images/FSF.png
  docs/images/MIT.png
  docs/images/apache.png
  docs/images/gpl.png
  docs/images/logo.md
  docs/images/mit.png
  docs/mahremiyet.md
Labels: documentation, enhancement, help wanted

#38 Tarayıcılar eklendi
  docs/_sidebar.md
  docs/arama-motorlari.md
  docs/images/brave-icon.png
  docs/images/firefox.png
  docs/images/librewolf.svg
  docs/images/mullvad-icon.png
  docs/images/tor.svg
  docs/internet-tarayicilari.md
  docs/web-tarayicilari.md
Labels: documentation, enhancement, help wanted

#40 Sağlayıcılar kategorisi genel düzenlemeler ve eklemeler
  docs/arama-motorlari.md
  docs/images/duckduckgo-icon.png
  docs/images/mullvadvpn-icon.png
  docs/images/proton-mail.png
  docs/images/protonmail.svg
  docs/images/protonvpn-icon.png
  docs/images/searx-icon.png
  docs/images/startpage-icon.png
  docs/images/thunderbird.png
  docs/images/tutamail.png
  docs/images/tutanota-mail.png
  docs/posta-servisleri.md
  docs/vpn.md
Labels: documentation, enhancement

#41 Tarayıcı Eklentileri sayfası eklendi ve genel eklemeler yapıldı.
  docs/_sidebar.md
  docs/arama-motorlari.md
  docs/images/sponsorblock.png
  docs/images/ublock.png
  docs/internet-tarayicilari.md
  docs/tarayici-eklentileri.md
Labels: documentation, enhancement

#64 İnternet Tarayıcısı Eklemesi
  docs/acik-kaynak.md
  docs/images/ug-chromium.png
  docs/internet-tarayicilari.md
  docs/katkida-bulunanlar.md
Labels: documentation, enhancement

#68 Düzeltme ve eklemeler
  docs/2-faktorlu-dogrulama.md
  docs/_sidebar.md
  docs/ceviri-araclari.md
  docs/dosya-aktarma.md
  docs/dosya-depolama.md
  docs/dosya-donusturme.md
  docs/dosya-sifreleme.md
  docs/dosya-sikistirma.md
  docs/ekleme.md
  docs/haritalar.md
  docs/kripto-cuzdanlari.md
  docs/mesajlasma-uygulamalari.md
  docs/not-alma.md
  docs/ofis-uygulamalari.md
  docs/rss-istemcileri.md
  docs/senkronizasyon.md
  docs/sifre-yoneticileri.md
  docs/sosyal-aglar.md
  docs/takvim-uygulamalari.md
  docs/torrent-istemcileri.md
  docs/yapay-zeka.md
Labels: geliştirme

#70 Şifre yöneticileri eklendi
  docs/README.md
  docs/guvenlik.md
  docs/images/bitwarden.png
  docs/images/keepassxc.png
  docs/images/vaultwarden.png
  docs/sifre-yoneticileri.md
Labels: dökümantasyon, geliştirme

#73 Update posta-servisleri.md
  docs/posta-servisleri.md
Labels: dökümantasyon, geliştirme

#74 Update mahremiyet.md
  docs/mahremiyet.md
Labels: dökümantasyon, geliştirme

#76 Update tarayici-eklentileri.md
  docs/tarayici-eklentileri.md
Labels: dökümantasyon, geliştirme

#77 Update vpn.md
  docs/vpn.md
Labels: dökümantasyon, geliştirme

#81 İşletim sistemleri kategorisi eklendi genel düzeltmeler yapıldı
  docs/README.md
  docs/_sidebar.md
  docs/android.md
  docs/masaustu-bilgisayar.md
  docs/modem-yazilimlari.md
  docs/posta-servisleri.md
  docs/tarayici-eklentileri.md
  docs/windows-guvenligi.md
Labels: dökümantasyon, geliştirme

#83 docs: posta-servisleri.md
  docs/posta-servisleri.md
Labels: dökümantasyon, geliştirme

#85 Firefox için ileri okuma makalesi eklendi.
  docs/internet-tarayicilari.md
Labels: dökümantasyon, geliştirme

#88 Geliştirme ortamı iyileştirmeleri
  .markdownlint.json
  .vscode/extensions.json
  .vscode/terminals.json
  CONTRIBUTING.md
  docs/README.md
  docs/_sidebar.md
  docs/android.md
  docs/arama-motorlari.md
  docs/bicimlendirme.md
  docs/dns.md
  docs/dosya-aktarma.md
  docs/ekleme.md
  docs/guvenlik.md
  docs/icerik-kurallari.md
  docs/internet-tarayicilari.md
  docs/katkida-bulunanlar.md
  docs/kriterler.md
  docs/mahremiyet.md
  docs/masaustu-bilgisayar.md
  docs/mesajlasma-uygulamalari.md
  docs/modem-yazilimlari.md
  docs/posta-servisleri.md
  docs/senkronizasyon.md
  docs/sifre-yoneticileri.md
  docs/takvim-uygulamalari.md
  docs/tarayici-eklentileri.md
  docs/tor-agi.md
  docs/vpn.md
  docs/windows-guvenligi.md
Labels: geliştirme

#89 DNS değiştirme için router/modem seçeneğinin eklenmesi
  docs/dns.md
  docs/katkida-bulunanlar.md
Labels: dökümantasyon, geliştirme

#91 Ana sayfa güncellendi
  docs/README.md
Labels: dökümantasyon, geliştirme

#95 Yazım hatasını düzelt
  docs/ekleme.md
Labels: dökümantasyon

#96 Docsify'a arama yapma özelliğinin eklenmesi
  index.html
Labels: geliştirme

#103 Sözlük eklendi
  docs/_sidebar.md
  docs/sozluk.md
Labels: dökümantasyon, geliştirme

#104 Anasayfaya kwalletmanager eklendi
  docs/README.md
Labels: dökümantasyon, geliştirme

#105 Hatalı link düzeltildi
  docs/ekleme.md
Labels: dökümantasyon

#106 Yazım hatası düzeltmesi ve link eklemesi
  docs/sifre-yoneticileri.md
Labels: dökümantasyon
